### ISSUE TITLE
Boiler goes wild when mqtt/wifi connection is lost

### ISSUE THREAD

**Issue by ericfennis** [diyless/home-assistant-opentherm-thermostat#11]
I had this a couple of times when MQTT/Wi-Fi connection was lost, my boiler went wild. 
My boiler goes full heat mode, which scares me a lot that I need to shut everything down to ensure it's not overheating.

Are there more people having this?

**Comment by ihormelnyk** [comment]
Hi @ericfennis ,
1. You can limit the heating temperature on the boiler.
2. It is better to use more complex firmware than a sample script which has a separate task for the OT loop and does not stop on Wi-Fi issues. The firmware for this product https://diyless.com/product/opentherm-thermostat costs 12 EUR if you want to buy it separately.

**Comment by ericfennis** [comment]
@ihormelnyk Tnx for your message and the solutions.
I bought already the Master OpenTherm Shield. 
Does the complex software not come with that board?

**Comment by diyless** [comment]
Hi @ericfennis ,
The Master OpenTherm Shield price includes the PCB itself only, you can use samples from the OpenTherm Library and sketches from our blog https://diyless.com/Blog
The OpenTherm Thermostat  https://diyless.com/product/opentherm-thermostat includes firmware, esp32 module, BLE sensor.

**Comment by ericfennis** [comment]
@diyless @ihormelnyk Thanks for your comments. I'm willing to pay the extra 12 euro for the more complex software.

Where can I buy it?

**Comment by diyless** [comment]
Hi @ericfennis ,
You can buy it here https://diyless.com/product/opentherm-thermostat-firmware
The total sum will be 12 euros.
Please provide a valid email address and we will send the activation code for flashing the firmware.

**Comment by ericfennis** [comment]
@diyless Thanks for the link. I don't see anything on the page about Home Assistant. Does this firmware still work with Home Assistant?

**Comment by diyless** [comment]
Hi @ericfennis ,
Yes, it is firmware for this product
https://diyless.com/product/opentherm-thermostat
configuration
https://diyless.com/blog/opentherm-thermostat-cfg-overview
To flash the firmware you need to have WeMos D1 mini ESP32 and Master OpenTherm Shield, BLE sensor optional

**Comment by ericfennis** [comment]
Awesome! Will buy it now.
