### ISSUE TITLE
Ki and Kp are swapped on web ui

### ISSUE THREAD

**Issue by RomanDidenko** [diyless/home-assistant-opentherm-thermostat#12]
Ki and Kp are swapped on web UI:

![image](https://github.com/diyless/home-assistant-opentherm-thermostat/assets/4664877/d7ee0d06-d1b4-4d67-86b8-0c00e2140d7b)

**Comment by diyless** [comment]
Hi @RomanDidenko ,
The issue will be fixed in the next version.
Thanks

**Comment by tshcherban** [comment]
Fixed, feel free to close the issue.
