### ISSUE TITLE
Opentherm Controller stops working

### ISSUE THREAD

**Issue by davidrustingha** [diyless/home-assistant-opentherm-thermostat#6]
I have an issue with the Opentherm Controller where it sometimes stops sending/receiving data. The only thing I have is the MQTT log sensor and it says 'Invalid Boiler Response 0'. 

Is there any way to retrieve the current log? Maybe a way to combine a websever with the MQTT functions?

Please help!

**Comment by iron-LAN** [comment]
The weird thing is that when I powerup the ESP8266 my boiler starts heating the water as if a temperature has just been set.

**Comment by tshcherban** [comment]
Logs can be obtained if you connect esp to the PC via usb cable, it would write all the info in Serial
